grammar Document;
import Statements;

// The optional EOL must be included since a document read in from a file will
// include one but a document generated by the formatter will not.
document: component EOL? EOF;
